version: '3'

services:
  # Configuración del servicio de la base de datos MongoDB
  databaseMongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seba
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  # Configuración del servicio de la base de datos MySQL
  database: 
    image: mysql:8.0.33
    container_name: my-database-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
    ports:
      - 3306:3306
    volumes:
      - ./dbdata/mysql:/var/lib/mysql

  # Configuración del servicio del servidor Express
  servidor:
    container_name: express-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: tienda
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./server:/server

volumes:
  mongo-data:
